export default [
  {
    label: 'Dashboard',
    href: '/dashboard',
    icon: 'bi-house',
    menuContext: 'global',
  },
  {
    label: 'Users',
    href: '/dashboard/users',
    icon: 'bi-people',
    roles: ['system_owner'],
    menuContext: 'system_owner',
  },
  {
    label: 'Roles',
    href: '/dashboard/roles',
    icon: 'bi-people',
    roles: ['system_owner'],
    menuContext: 'system_owner',
  },
  {
    label: 'Foundations',
    href: '/dashboard/foundations',
    icon: 'bi-people',
    roles: ['system_owner'],
    menuContext: 'system_owner',
  },
  {
    label: 'Units',
    href: '/dashboard/units',
    icon: 'bi-people',
    roles: ['system_owner'],
    menuContext: 'system_owner',
  },
  {
    label: 'Unit Type',
    href: '/dashboard/unit_types',
    icon: 'bi-people',
    roles: ['system_owner'],
    menuContext: 'system_owner',
  },
  {
    label: 'Levels',
    href: '/dashboard/levels',
    icon: 'bi-people',
    roles: ['system_owner'],
    menuContext: 'system_owner',
  },
  {
    label: 'Class Levels',
    href: '/dashboard/class_levels',
    icon: 'bi-people',
    roles: ['system_owner'],
    menuContext: 'system_owner',
  },
  {
    label: 'Reports',
    href: '/reports',
    icon: 'bi-bar-chart',
    roles: ['admin', 'staff'],
    menuContext: 'system_owner',
  },
];
