//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Status;
use chrono::NaiveDate;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "applicants")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64, // Primary key
    pub foundation_id: i64,
    pub date_in: NaiveDate,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: String,
    pub birth_place: String,
    pub birth_date: NaiveDate,
    pub gender: String,
    pub status: Status,
    pub email: Option<String>,
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
impl ActiveModelBehavior for ActiveModel {}
