//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "class_schedules")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub class_subject_id: i64,
    pub time_slot_id: i64,
    pub room_id: Option<i64>,
    pub teacher_id: Option<i64>,
    pub is_auto_generated: Option<i8>,
    pub generation_batch_id: Option<String>,
    pub conflict_score: Option<i32>,
    pub status: Option<Status>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::class_subjects::Entity",
        from = "Column::ClassSubjectId",
        to = "super::class_subjects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ClassSubjects,
    #[sea_orm(
        belongs_to = "super::rooms::Entity",
        from = "Column::RoomId",
        to = "super::rooms::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Rooms,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::TeacherId",
        to = "super::teachers::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Teachers,
    #[sea_orm(
        belongs_to = "super::time_slots::Entity",
        from = "Column::TimeSlotId",
        to = "super::time_slots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TimeSlots,
}

impl Related<super::class_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSubjects.def()
    }
}

impl Related<super::rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rooms.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl Related<super::time_slots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimeSlots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
