//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Grade;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extracurricular_enrollments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub foundation_id: i64,
    pub student_id: i64,
    pub extracurricular_id: i64,
    pub semester_id: i64,
    pub grade: Option<Grade>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
