//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
// backend/entity/src/foundation_regulations.rs
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "foundation_regulations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub foundation_id: i64,
    pub regulation_id: i64,
    pub is_active: Option<i8>,
    pub config: Option<Json>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::foundations::Entity",
        from = "Column::FoundationId",
        to = "super::foundations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Foundations,
    #[sea_orm(
        belongs_to = "super::regulations::Entity",
        from = "Column::RegulationId",
        to = "super::regulations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Regulations,
}

impl Related<super::foundations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Foundations.def()
    }
}

impl Related<super::regulations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Regulations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
