//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Predicate;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "grades")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub student_id: i64,
    pub class_subject_id: i64,
    pub semester_id: i64,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub attendance_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub assignment_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub quiz_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub midterm_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub final_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub final_grade: Decimal,
    pub grade_letter: Option<String>,
    pub predicate: Option<Predicate>,
    #[sea_orm(column_type = "Text", nullable)]
    pub teacher_notes: Option<String>,
    pub is_finalized: Option<i8>,
    pub finalized_at: Option<DateTimeUtc>,
    pub finalized_by: Option<i64>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
impl ActiveModelBehavior for ActiveModel {}
