//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
// backend/entity/src/permissions.rs
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "permissions")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    pub foundation_id: i64,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub code: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, DeriveRelation, EnumIter)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::foundations::Entity",
        from = "Column::FoundationId",
        to = "super::foundations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Foundations,

    #[sea_orm(has_many = "super::role_permissions::Entity")]
    RolePermissions,

    #[sea_orm(has_many = "super::user_permissions::Entity")]
    UserPermissions,
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::role_permissions::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::role_permissions::Relation::Permissions.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_permissions::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_permissions::Relation::Permissions.def().rev())
    }
}

// Tambahkan ini jika belum ada untuk memudahkan join manual
impl Related<super::role_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::role_permissions::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::role_permissions::Relation::Permissions.def().rev())
    }
}

impl Related<super::user_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_permissions::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_permissions::Relation::Permissions.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
// ✅ Implementasi trait SoftDelete
impl crate::traits::soft_delete::SoftDelete for Entity {
    fn deleted_at_col() -> Column {
        Column::DeletedAt
    }
}
