//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::notifications::Entity as Notifications;
pub use super::role_users::Entity as RoleUsers;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
