//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "report_cards")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub student_id: i64,
    pub class_id: i64,
    pub semester_id: i64,
    pub academic_year_id: i64,
    pub class_rank: Option<i32>,
    pub total_students: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub average_score: Option<Decimal>,
    pub total_absences: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub homeroom_teacher_notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub principal_notes: Option<String>,
    pub status: Option<Status>,
    pub finalized_at: Option<DateTimeUtc>,
    pub finalized_by: Option<i64>,
    pub printed_count: Option<i32>,
    pub last_printed_at: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
impl ActiveModelBehavior for ActiveModel {}
