//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
use sea_orm::entity::prelude::*; // ← Import dari entity crate

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_users::Entity")]
    RoleUsers,
}

impl Related<super::role_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
// ✅ Implementasi trait SoftDelete
impl crate::traits::soft_delete::SoftDelete for Entity {
    fn deleted_at_col() -> Column {
        Column::DeletedAt
    }
}

// ini saya matikan karena di line 19 sudah ada #[derive(DeriveRelation)]
// DeriveRelation artinya tidak perlu membuat impl RelationTrait manual
// impl RelationTrait for Relation {
//     fn def(&self) -> RelationDef {
//         match self {
//             Self::RoleUsers => Entity::has_many(super::role_users::Entity).into(),
//         }
//     }
// }
