//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: u64,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_users::Entity")]
    RoleUsers,
}

impl Related<super::role_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

// impl RelationTrait for Relation {
//     fn def(&self) -> RelationDef {
//         match self {
//             Self::RoleUsers => Entity::has_many(super::role_users::Entity).into(),
//         }
//     }
// }
