//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
// backend/entity/src/roles.rs
use sea_orm::entity::prelude::*; // ← Import dari entity crate
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    pub foundation_id: i64,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(column_type = "Text", nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_users::Entity")]
    RoleUsers,
    #[sea_orm(has_many = "super::role_permissions::Entity")]
    RolePermissions,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::role_users::Relation::Users.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::users::Relation::RoleUsers.def().rev())
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::role_permissions::Relation::Permissions.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::permissions::Relation::RolePermissions.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
// ✅ Implementasi trait SoftDelete
impl crate::traits::soft_delete::SoftDelete for Entity {
    fn deleted_at_col() -> Column {
        Column::DeletedAt
    }
}
