//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "salary_payments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub teacher_salary_id: i64,
    pub payment_period_month: i32,
    pub payment_period_year: i32,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub base_salary: Decimal,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub total_allowances: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub total_deductions: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub gross_salary: Decimal,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub net_salary: Decimal,
    pub working_days: Option<i32>,
    pub present_days: Option<i32>,
    pub absent_days: Option<i32>,
    pub late_days: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub bonus: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub penalty: Option<Decimal>,
    pub payment_status: Option<String>,
    pub payment_date: Option<Date>,
    pub payment_method: Option<String>,
    pub approved_by: Option<i64>,
    pub approved_at: Option<DateTimeUtc>,
    pub paid_by: Option<i64>,
    pub paid_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::teacher_salaries::Entity",
        from = "Column::TeacherSalaryId",
        to = "super::teacher_salaries::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TeacherSalaries,
}

impl Related<super::teacher_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherSalaries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
