//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "schedule_generation_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub batch_id: String,
    pub semester_id: i64,
    pub unit_id: i64,
    pub algorithm: Option<String>,
    pub total_slots_needed: Option<i32>,
    pub total_slots_filled: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub success_rate: Option<Decimal>,
    pub conflicts_detected: Option<Json>,
    pub execution_time_ms: Option<i32>,
    pub status: Option<Status>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub created_by: Option<i64>,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
impl ActiveModelBehavior for ActiveModel {}
