//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use chrono::NaiveDate;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "semesters")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub foundation_id: i64,
    pub unit_id: i64,
    pub academic_calendar_id: i64,
    pub name: String,
    pub year: i32,
    pub semester_number: i8,
    pub start_date: NaiveDate,
    pub end_date: NaiveDate,
    pub is_active: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
