//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "students")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub user_id: i64,
    pub name: String,
    pub foundation_id: i64,
    pub unit_id: Option<i64>,
    pub student_number: String,
    pub class_id: Option<i64>,
    pub parent_name: Option<String>,
    pub parent_phone: Option<String>,
    pub enrollment_date: Option<DateTimeUtc>,
    pub graduation_date: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {} 

impl ActiveModelBehavior for ActiveModel {}
