//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::EmploymentStatus;
use chrono::NaiveDate;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "teachers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub user_id: i64,
    pub name: String,
    pub foundation_id: i64,
    pub unit_id: Option<i64>,
    pub nik: Option<String>,
    pub employee_number: String,
    pub specialization: Option<String>,
    pub qualification: Option<String>,
    // Date
    // "2024-01-15"
    // └─ tahun─┘ │ └─ hari
    //             └─ bulan
    pub hire_date: Option<NaiveDate>,
    pub end_date: Option<NaiveDate>,
    pub salary: Option<String>,
    pub employment_status: Option<EmploymentStatus>,
    // DateTimeUtc
    // "2024-01-15T10:30:45.123456789Z"
    // └─ tahun─┘ │ │  │  │  └─ nanodetik
    //             │ │  │  └─ detik
    //             │ │  └─ menit
    //             │ └─ jam
    //             └─ bulan-hari
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
