//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod class_levels;
pub mod classes;
pub mod foundations;
pub mod levels;
pub mod notifications;
pub mod permissions;
pub mod role_permissions;
pub mod role_users;
pub mod roles;
pub mod students;
pub mod teachers;
pub mod unit_types;
pub mod units;
pub mod users;
