//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::class_levels::Entity as ClassLevels;
pub use super::classes::Entity as Classes;
pub use super::foundations::Entity as Foundations;
pub use super::levels::Entity as Levels;
pub use super::notifications::Entity as Notifications;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::role_users::Entity as RoleUsers;
pub use super::roles::Entity as Roles;
pub use super::students::Entity as Students;
pub use super::teachers::Entity as Teachers;
pub use super::unit_types::Entity as UnitTypes;
pub use super::units::Entity as Units;
pub use super::users::Entity as Users;
