//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "teacher_availability")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub teacher_id: u64,
    pub time_slot_id: u64,
    pub is_available: Option<i8>,
    pub reason: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::TeacherId",
        to = "super::teachers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Teachers,
    #[sea_orm(
        belongs_to = "super::time_slots::Entity",
        from = "Column::TimeSlotId",
        to = "super::time_slots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TimeSlots,
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl Related<super::time_slots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimeSlots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
