//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "academic_years")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub foundation_id: i64,
    pub name: String,
    pub start_date: Date,
    pub end_date: Date,
    pub is_active: Option<i8>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::classrooms::Entity")]
    Classrooms,
    #[sea_orm(has_many = "super::extracurriculars::Entity")]
    Extracurriculars,
    #[sea_orm(
        belongs_to = "super::foundations::Entity",
        from = "Column::FoundationId",
        to = "super::foundations::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Foundations,
    #[sea_orm(has_many = "super::homeroom_teachers::Entity")]
    HomeroomTeachers,
    #[sea_orm(has_many = "super::report_cards::Entity")]
    ReportCards,
    #[sea_orm(has_many = "super::semesters::Entity")]
    Semesters,
    #[sea_orm(has_many = "super::teacher_assignments::Entity")]
    TeacherAssignments,
    #[sea_orm(has_many = "super::teacher_subjects::Entity")]
    TeacherSubjects,
}

impl Related<super::classrooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classrooms.def()
    }
}

impl Related<super::extracurriculars::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extracurriculars.def()
    }
}

impl Related<super::foundations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Foundations.def()
    }
}

impl Related<super::homeroom_teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HomeroomTeachers.def()
    }
}

impl Related<super::report_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportCards.def()
    }
}

impl Related<super::semesters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Semesters.def()
    }
}

impl Related<super::teacher_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherAssignments.def()
    }
}

impl Related<super::teacher_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherSubjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
