//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "attendances")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub student_id: u64,
    pub class_subject_id: u64,
    pub date: Date,
    pub status: Status,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::class_subjects::Entity",
        from = "Column::ClassSubjectId",
        to = "super::class_subjects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ClassSubjects,
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Students,
}

impl Related<super::class_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSubjects.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
