//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Grade;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "character_assessments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub student_id: i64,
    pub semester_id: i64,
    pub character_trait_id: i64,
    pub grade: Grade,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub assessed_by: Option<i64>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::character_traits::Entity",
        from = "Column::CharacterTraitId",
        to = "super::character_traits::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    CharacterTraits,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::SemesterId",
        to = "super::semesters::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Semesters,
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Students,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::AssessedBy",
        to = "super::teachers::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Teachers,
}

impl Related<super::character_traits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterTraits.def()
    }
}

impl Related<super::semesters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Semesters.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
