//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "classes")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub class_level_id: Option<i32>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::class_subjects::Entity")]
    ClassSubjects,
    #[sea_orm(has_many = "super::report_cards::Entity")]
    ReportCards,
    #[sea_orm(has_many = "super::students::Entity")]
    Students,
}

impl Related<super::class_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSubjects.def()
    }
}

impl Related<super::report_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportCards.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
