//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "class_subjects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub class_id: i64,
    pub subject_id: i64,
    pub semester_id: i64,
    pub teacher_id: Option<i64>,
    pub credit_hours: Option<i32>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attendances::Entity")]
    Attendances,
    #[sea_orm(has_many = "super::class_schedules::Entity")]
    ClassSchedules,
    #[sea_orm(
        belongs_to = "super::classes::Entity",
        from = "Column::ClassId",
        to = "super::classes::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Classes,
    #[sea_orm(has_many = "super::grades::Entity")]
    Grades,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::SemesterId",
        to = "super::semesters::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Semesters,
    #[sea_orm(
        belongs_to = "super::subjects::Entity",
        from = "Column::SubjectId",
        to = "super::subjects::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Subjects,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::TeacherId",
        to = "super::teachers::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Teachers,
}

impl Related<super::attendances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attendances.def()
    }
}

impl Related<super::class_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSchedules.def()
    }
}

impl Related<super::classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classes.def()
    }
}

impl Related<super::grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Grades.def()
    }
}

impl Related<super::semesters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Semesters.def()
    }
}

impl Related<super::subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subjects.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
