//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Score;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extracurricular_grades")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub extracurricular_enrollment_id: i64,
    pub semester_id: i64,
    pub score: Score,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::extracurricular_enrollments::Entity",
        from = "Column::ExtracurricularEnrollmentId",
        to = "super::extracurricular_enrollments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ExtracurricularEnrollments,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::SemesterId",
        to = "super::semesters::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Semesters,
}

impl Related<super::extracurricular_enrollments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtracurricularEnrollments.def()
    }
}

impl Related<super::semesters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Semesters.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
