//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::FoundationType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "foundations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(unique)]
    pub code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub foundation_type: Option<FoundationType>,
    pub parent_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    pub city: Option<String>,
    pub province: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub is_active: Option<i8>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::academic_years::Entity")]
    AcademicYears,
    #[sea_orm(has_many = "super::employees::Entity")]
    Employees,
    #[sea_orm(has_many = "super::extracurricular_activities::Entity")]
    ExtracurricularActivities,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::role_users::Entity")]
    RoleUsers,
    #[sea_orm(has_many = "super::students::Entity")]
    Students,
    #[sea_orm(has_many = "super::subjects::Entity")]
    Subjects,
    #[sea_orm(has_many = "super::teachers::Entity")]
    Teachers,
    #[sea_orm(has_many = "super::time_slots::Entity")]
    TimeSlots,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::employees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employees.def()
    }
}

impl Related<super::extracurricular_activities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtracurricularActivities.def()
    }
}

impl Related<super::role_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleUsers.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subjects.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl Related<super::time_slots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimeSlots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
