//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Predicate;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "grades")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub student_id: i64,
    pub class_subject_id: i64,
    pub semester_id: i64,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub attendance_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub assignment_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub quiz_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub midterm_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub final_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub final_grade: Decimal,
    pub grade_letter: Option<String>,
    pub predicate: Option<Predicate>,
    #[sea_orm(column_type = "Text", nullable)]
    pub teacher_notes: Option<String>,
    pub is_finalized: Option<i8>,
    pub finalized_at: Option<DateTime>,
    pub finalized_by: Option<i64>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::class_subjects::Entity",
        from = "Column::ClassSubjectId",
        to = "super::class_subjects::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    ClassSubjects,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::SemesterId",
        to = "super::semesters::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Semesters,
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Students,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::FinalizedBy",
        to = "super::teachers::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Teachers,
}

impl Related<super::class_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSubjects.def()
    }
}

impl Related<super::semesters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Semesters.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
