//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "homeroom_teachers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub teacher_assignment_id: i64,
    pub classroom_id: i64,
    pub academic_year_id: i64,
    pub semester_id: Option<i64>,
    pub is_active: Option<i8>,
    pub assigned_at: Date,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AcademicYears,
    #[sea_orm(
        belongs_to = "super::classrooms::Entity",
        from = "Column::ClassroomId",
        to = "super::classrooms::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Classrooms,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::SemesterId",
        to = "super::semesters::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Semesters,
    #[sea_orm(
        belongs_to = "super::teacher_assignments::Entity",
        from = "Column::TeacherAssignmentId",
        to = "super::teacher_assignments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TeacherAssignments,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::classrooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classrooms.def()
    }
}

impl Related<super::semesters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Semesters.def()
    }
}

impl Related<super::teacher_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherAssignments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
