//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "report_card_details")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub report_card_id: i64,
    pub subject_id: i64,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub knowledge_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub skill_score: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub final_score: Option<Decimal>,
    pub grade: Option<String>,
    pub predicate: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::report_cards::Entity",
        from = "Column::ReportCardId",
        to = "super::report_cards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ReportCards,
    #[sea_orm(
        belongs_to = "super::subjects::Entity",
        from = "Column::SubjectId",
        to = "super::subjects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subjects,
}

impl Related<super::report_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportCards.def()
    }
}

impl Related<super::subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
