//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "report_cards")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub student_id: i64,
    pub class_id: i64,
    pub semester_id: i64,
    pub academic_year_id: i64,
    pub class_rank: Option<i32>,
    pub total_students: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub average_score: Option<Decimal>,
    pub total_absences: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub homeroom_teacher_notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub principal_notes: Option<String>,
    pub status: Option<Status>,
    pub finalized_at: Option<DateTime>,
    pub finalized_by: Option<i64>,
    pub printed_count: Option<i32>,
    pub last_printed_at: Option<DateTime>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    AcademicYears,
    #[sea_orm(
        belongs_to = "super::classes::Entity",
        from = "Column::ClassId",
        to = "super::classes::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Classes,
    #[sea_orm(
        belongs_to = "super::semesters::Entity",
        from = "Column::SemesterId",
        to = "super::semesters::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Semesters,
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Students,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::FinalizedBy",
        to = "super::users::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classes.def()
    }
}

impl Related<super::semesters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Semesters.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
