//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "room_facilities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub room_id: u64,
    pub facility_id: u64,
    pub foundation_id: Option<u64>,
    pub qty: Option<i32>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::facilities::Entity",
        from = "Column::FacilityId",
        to = "super::facilities::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Facilities,
    #[sea_orm(
        belongs_to = "super::rooms::Entity",
        from = "Column::RoomId",
        to = "super::rooms::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rooms,
}

impl Related<super::facilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Facilities.def()
    }
}

impl Related<super::rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rooms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
