//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "salary_grades")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub foundation_id: i64,
    pub name: String,
    #[sea_orm(unique)]
    pub code: String,
    pub education_level: Option<String>,
    pub min_years_experience: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub base_salary: Decimal,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::foundations::Entity",
        from = "Column::FoundationId",
        to = "super::foundations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Foundations,
    #[sea_orm(has_many = "super::teacher_salaries::Entity")]
    TeacherSalaries,
}

impl Related<super::foundations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Foundations.def()
    }
}

impl Related<super::teacher_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherSalaries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
