//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "employment_status")]
pub enum EmploymentStatus {
    #[sea_orm(string_value = "permanent")]
    Permanent,
    #[sea_orm(string_value = "contract")]
    Contract,
    #[sea_orm(string_value = "freelance")]
    Freelance,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "employment_type")]
pub enum EmploymentType {
    #[sea_orm(string_value = "permanent")]
    Permanent,
    #[sea_orm(string_value = "contract")]
    Contract,
    #[sea_orm(string_value = "daily")]
    Daily,
    #[sea_orm(string_value = "freelance")]
    Freelance,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "foundation_type")]
pub enum FoundationType {
    #[sea_orm(string_value = "pusat")]
    Pusat,
    #[sea_orm(string_value = "cabang")]
    Cabang,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gender")]
pub enum Gender {
    #[sea_orm(string_value = "m")]
    M,
    #[sea_orm(string_value = "f")]
    F,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "grade")]
pub enum Grade {
    #[sea_orm(string_value = "A")]
    A,
    #[sea_orm(string_value = "B")]
    B,
    #[sea_orm(string_value = "C")]
    C,
    #[sea_orm(string_value = "D")]
    D,
    #[sea_orm(string_value = "E")]
    E,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "membership_type")]
pub enum MembershipType {
    #[sea_orm(string_value = "basic")]
    Basic,
    #[sea_orm(string_value = "premium")]
    Premium,
    #[sea_orm(string_value = "vip")]
    Vip,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "predicate")]
pub enum Predicate {
    #[sea_orm(string_value = "Sangat Baik")]
    SangatBaik,
    #[sea_orm(string_value = "Baik")]
    Baik,
    #[sea_orm(string_value = "Cukup")]
    Cukup,
    #[sea_orm(string_value = "Kurang")]
    Kurang,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "preference_level")]
pub enum PreferenceLevel {
    #[sea_orm(string_value = "preferred")]
    Preferred,
    #[sea_orm(string_value = "neutral")]
    Neutral,
    #[sea_orm(string_value = "avoid")]
    Avoid,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "required_room_type")]
pub enum RequiredRoomType {
    #[sea_orm(string_value = "classroom")]
    Classroom,
    #[sea_orm(string_value = "lab")]
    Lab,
    #[sea_orm(string_value = "hall")]
    Hall,
    #[sea_orm(string_value = "library")]
    Library,
    #[sea_orm(string_value = "outdoor")]
    Outdoor,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "scope_level")]
pub enum ScopeLevel {
    #[sea_orm(string_value = "system")]
    System,
    #[sea_orm(string_value = "foundation")]
    Foundation,
    #[sea_orm(string_value = "unit")]
    Unit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "slot_type")]
pub enum SlotType {
    #[sea_orm(string_value = "lesson")]
    Lesson,
    #[sea_orm(string_value = "break")]
    Break,
    #[sea_orm(string_value = "extracurricular")]
    Extracurricular,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "transferred")]
    Transferred,
    #[sea_orm(string_value = "graduated")]
    Graduated,
    #[sea_orm(string_value = "dropped")]
    Dropped,
}
