//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "semesters")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub academic_year_id: u64,
    pub name: String,
    pub semester_number: i8,
    pub start_date: Date,
    pub end_date: Date,
    pub is_active: Option<i8>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AcademicYears,
    #[sea_orm(has_many = "super::character_assessments::Entity")]
    CharacterAssessments,
    #[sea_orm(has_many = "super::class_subjects::Entity")]
    ClassSubjects,
    #[sea_orm(has_many = "super::extracurricular_enrollments::Entity")]
    ExtracurricularEnrollments,
    #[sea_orm(has_many = "super::grades::Entity")]
    Grades,
    #[sea_orm(has_many = "super::report_cards::Entity")]
    ReportCards,
    #[sea_orm(has_many = "super::schedule_generation_logs::Entity")]
    ScheduleGenerationLogs,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::character_assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterAssessments.def()
    }
}

impl Related<super::class_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSubjects.def()
    }
}

impl Related<super::extracurricular_enrollments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtracurricularEnrollments.def()
    }
}

impl Related<super::grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Grades.def()
    }
}

impl Related<super::report_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportCards.def()
    }
}

impl Related<super::schedule_generation_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduleGenerationLogs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
