//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "subjects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub foundation_id: i64,
    pub code: Option<String>,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub credit_hours: Option<i32>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::class_subjects::Entity")]
    ClassSubjects,
    #[sea_orm(
        belongs_to = "super::foundations::Entity",
        from = "Column::FoundationId",
        to = "super::foundations::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Foundations,
    #[sea_orm(has_many = "super::report_card_details::Entity")]
    ReportCardDetails,
    #[sea_orm(has_many = "super::subject_preferences::Entity")]
    SubjectPreferences,
    #[sea_orm(has_many = "super::subject_room_requirements::Entity")]
    SubjectRoomRequirements,
    #[sea_orm(has_many = "super::teacher_subjects::Entity")]
    TeacherSubjects,
}

impl Related<super::class_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSubjects.def()
    }
}

impl Related<super::foundations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Foundations.def()
    }
}

impl Related<super::report_card_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportCardDetails.def()
    }
}

impl Related<super::subject_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubjectPreferences.def()
    }
}

impl Related<super::subject_room_requirements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubjectRoomRequirements.def()
    }
}

impl Related<super::teacher_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherSubjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
