//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::PreferenceLevel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "subject_preferences")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub subject_id: u64,
    pub time_slot_id: u64,
    pub preference_level: Option<PreferenceLevel>,
    pub reason: Option<String>,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::subjects::Entity",
        from = "Column::SubjectId",
        to = "super::subjects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subjects,
    #[sea_orm(
        belongs_to = "super::time_slots::Entity",
        from = "Column::TimeSlotId",
        to = "super::time_slots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TimeSlots,
}

impl Related<super::subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subjects.def()
    }
}

impl Related<super::time_slots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimeSlots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
