//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::EmploymentStatus;
use super::sea_orm_active_enums::Gender;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "teachers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub user_id: i64,
    pub foundation_id: i64,
    pub unit_id: Option<i64>,
    pub nik: Option<String>,
    pub nip: Option<String>,
    pub employee_number: String,
    pub specialization: Option<String>,
    pub qualification: Option<String>,
    pub hire_date: Option<Date>,
    pub end_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))", nullable)]
    pub salary: Option<Decimal>,
    pub employment_status: Option<EmploymentStatus>,
    pub dob: Option<Date>,
    pub pob: Option<String>,
    pub gender: Option<Gender>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::character_assessments::Entity")]
    CharacterAssessments,
    #[sea_orm(has_many = "super::class_schedules::Entity")]
    ClassSchedules,
    #[sea_orm(has_many = "super::class_subjects::Entity")]
    ClassSubjects,
    #[sea_orm(
        belongs_to = "super::foundations::Entity",
        from = "Column::FoundationId",
        to = "super::foundations::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Foundations,
    #[sea_orm(has_many = "super::grades::Entity")]
    Grades,
    #[sea_orm(has_many = "super::teacher_assignments::Entity")]
    TeacherAssignments,
    #[sea_orm(has_many = "super::teacher_availability::Entity")]
    TeacherAvailability,
    #[sea_orm(
        belongs_to = "super::units::Entity",
        from = "Column::UnitId",
        to = "super::units::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Units,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::character_assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterAssessments.def()
    }
}

impl Related<super::class_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSchedules.def()
    }
}

impl Related<super::class_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClassSubjects.def()
    }
}

impl Related<super::foundations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Foundations.def()
    }
}

impl Related<super::grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Grades.def()
    }
}

impl Related<super::teacher_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherAssignments.def()
    }
}

impl Related<super::teacher_availability::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherAvailability.def()
    }
}

impl Related<super::units::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Units.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
