//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub foundation_id: Option<i32>,
    pub username: Option<String>,
    pub password: String,
    pub is_verified: Option<i8>,
    pub is_active: Option<i32>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::employees::Entity")]
    Employees,
    #[sea_orm(has_one = "super::members::Entity")]
    Members,
    #[sea_orm(has_many = "super::report_cards::Entity")]
    ReportCards,
    #[sea_orm(has_many = "super::role_users::Entity")]
    RoleUsers,
    #[sea_orm(has_many = "super::schedule_generation_logs::Entity")]
    ScheduleGenerationLogs,
    #[sea_orm(has_one = "super::students::Entity")]
    Students,
    #[sea_orm(has_one = "super::teachers::Entity")]
    Teachers,
    #[sea_orm(has_one = "super::user_profiles::Entity")]
    UserProfiles,
}

impl Related<super::employees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employees.def()
    }
}

impl Related<super::members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Members.def()
    }
}

impl Related<super::report_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportCards.def()
    }
}

impl Related<super::role_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleUsers.def()
    }
}

impl Related<super::schedule_generation_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduleGenerationLogs.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl Related<super::user_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProfiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
