//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::traits::Tenanted;
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use sea_orm::{entity::prelude::*, Set};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "boarding_schools")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    pub foundation_id: i64,
    pub name: String,
    pub level_id: Option<i32>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// ✅ Implementasi yang benar untuk v2.0-rc
#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let now = Utc::now().into();
        if insert {
            self.created_at = Set(now);
        }
        self.updated_at = Set(now);
        Ok(self)
    }
}
impl Model {
    pub fn new(name: &str, foundation_id: i64) -> Self {
        Self {
            id: 0,
            foundation_id,
            name: name.to_string(),
            level_id: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
        }
    }

    // Keuntungan Menggunakan Fungsi Ini
    // Lebih ringkas & rapi
    // Tidak perlu menulis ulang kueri lengkap di tempat lain, cukup panggil:
    pub fn find_by_name(name: &str) -> Select<Entity> {
        Entity::find().filter(Column::Name.eq(name))
    }

    pub fn find_by_id(id: i64) -> Select<Entity> {
        Entity::find().filter(Column::Id.eq(id))
    }

    pub fn find_by_foundation_id(foundation_id: i64) -> Select<Entity> {
        Entity::find().filter(Column::FoundationId.eq(foundation_id))
    }

    pub fn find_by_foundation_id_and_name(foundation_id: i64, name: &str) -> Select<Entity> {
        Entity::find()
            .filter(Column::FoundationId.eq(foundation_id))
            .filter(Column::Name.eq(name))
    }

    pub fn find_by_foundation_id_and_level_id(foundation_id: i64, level_id: i32) -> Select<Entity> {
        Entity::find()
            .filter(Column::FoundationId.eq(foundation_id))
            .filter(Column::LevelId.eq(level_id))
    }
}

impl Tenanted for Entity {
    type Col = Column;
    fn foundation_id_column() -> Self::Col {
        Column::FoundationId
    }
}

// ✅ Implementasi trait SoftDelete
impl crate::traits::soft_delete::SoftDelete for Entity {
    fn deleted_at_col() -> Column {
        Column::DeletedAt
    }
}

// Daripada tulis begini setiap kali:
// let hasil = Entity::find().filter(Column::Name.eq("Andrea")).all(&db).await;

// Cukup tulis ini:
// let hasil = Model::find_by_name("Andrea").all(&db).await;

// Atau
// let hasil = Model::find_by_name("Andrea").one(&db).await;
