//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "classrooms")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub academic_year_id: i64,
    pub grade_level: i8,
    pub name: String,
    pub homeroom_teacher_id: Option<i64>,
    pub capacity: Option<i32>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AcademicYears,
    #[sea_orm(has_many = "super::homeroom_teachers::Entity")]
    HomeroomTeachers,
    #[sea_orm(has_many = "super::teacher_subjects::Entity")]
    TeacherSubjects,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::homeroom_teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HomeroomTeachers.def()
    }
}

impl Related<super::teacher_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherSubjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
