//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "teacher_salaries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub teacher_assignment_id: i64,
    pub salary_grade_id: i64,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub base_salary: Decimal,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub position_allowance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub teaching_allowance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub certification_allowance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub performance_allowance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub transport_allowance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub meal_allowance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub other_allowances: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub tax_deduction: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub insurance_deduction: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub loan_deduction: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub other_deductions: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub gross_salary: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub net_salary: Option<Decimal>,
    pub effective_date: Date,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::salary_grades::Entity",
        from = "Column::SalaryGradeId",
        to = "super::salary_grades::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SalaryGrades,
    #[sea_orm(has_many = "super::salary_payments::Entity")]
    SalaryPayments,
    #[sea_orm(
        belongs_to = "super::teacher_assignments::Entity",
        from = "Column::TeacherAssignmentId",
        to = "super::teacher_assignments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TeacherAssignments,
}

impl Related<super::salary_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryGrades.def()
    }
}

impl Related<super::salary_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalaryPayments.def()
    }
}

impl Related<super::teacher_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherAssignments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
