//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "teacher_assignments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub teacher_id: i64,
    pub unit_id: i64,
    pub academic_year_id: i64,
    pub employment_status: String,
    pub employment_type: String,
    pub position: String,
    pub position_level: Option<String>,
    pub department_id: Option<i64>,
    pub teaching_hours_per_week: Option<i32>,
    pub max_teaching_hours: Option<i32>,
    pub assignment_start_date: Date,
    pub assignment_end_date: Option<Date>,
    pub is_active: Option<i8>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::academic_years::Entity",
        from = "Column::AcademicYearId",
        to = "super::academic_years::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AcademicYears,
    #[sea_orm(
        belongs_to = "super::departments::Entity",
        from = "Column::DepartmentId",
        to = "super::departments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Departments,
    #[sea_orm(has_many = "super::homeroom_teachers::Entity")]
    HomeroomTeachers,
    #[sea_orm(has_many = "super::teacher_salaries::Entity")]
    TeacherSalaries,
    #[sea_orm(has_many = "super::teacher_subjects::Entity")]
    TeacherSubjects,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::TeacherId",
        to = "super::teachers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Teachers,
    #[sea_orm(
        belongs_to = "super::units::Entity",
        from = "Column::UnitId",
        to = "super::units::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Units,
}

impl Related<super::academic_years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AcademicYears.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::homeroom_teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HomeroomTeachers.def()
    }
}

impl Related<super::teacher_salaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherSalaries.def()
    }
}

impl Related<super::teacher_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherSubjects.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl Related<super::units::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Units.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
