// Auto-generated by build.rs
// DO NOT EDIT MANUALLY

#![allow(unused_imports)]


#[macro_export]
        macro_rules! merge_api_docs {
            ($($doc:ty),* $(,)?) => {{
                let mut base_api = utoipa::openapi::OpenApiBuilder::new()
                    .info(
                        utoipa::openapi::InfoBuilder::new()
                            .title("My API")
                            .version("1.0.0")
                            .description(Some("Auto-generated API documentation"))
                            .build()
                    )
                    .build();

                $(
                    let doc = <$doc>::openapi();
                    base_api.paths.paths.extend(doc.paths.paths);

                    if let Some(components) = doc.components {
                        if let Some(base_components) = &mut base_api.components {
                            base_components.schemas.extend(components.schemas);
                        } else {
                            base_api.components = Some(components);
                        }
                    }

                    if let Some(tags) = doc.tags {
                        if let Some(base_tags) = &mut base_api.tags {
                            base_tags.extend(tags);
                        } else {
                            base_api.tags = Some(tags);
                        }
                    }
                )*

                base_api
            }};
        }

        #[macro_export]
        macro_rules! generate_openapi {
            () => {{
                merge_api_docs!(
                    crate::modules::academic_years::docs::AcademicYearsApiDoc,
            crate::modules::auth::docs::AuthApiDoc,
            crate::modules::foundations::docs::FoundationsApiDoc,
            crate::modules::roles::docs::RolesApiDoc,
            crate::modules::users::docs::UsersApiDoc,
        )
    }};
}
