// Auto-generated by build.rs
// DO NOT EDIT MANUALLY

pub mod academic_year_docs;
pub mod auth_docs;
pub mod role_docs;
pub mod user_docs;

/// Macro untuk auto-merge semua OpenAPI docs
#[macro_export]
macro_rules! merge_api_docs {
    ($($doc:ty),* $(,)?) => {{
        let mut base_api = utoipa::openapi::OpenApiBuilder::new()
            .info(
                utoipa::openapi::InfoBuilder::new()
                    .title("My API")
                    .version("1.0.0")
                    .description(Some("Auto-generated API documentation"))
                    .build()
            )
            .build();

        // Merge semua docs
        $(
            let doc = <$doc>::openapi();
            base_api.paths.paths.extend(doc.paths.paths);
            
            if let Some(components) = doc.components {
                if let Some(base_components) = &mut base_api.components {
                    base_components.schemas.extend(components.schemas);
                } else {
                    base_api.components = Some(components);
                }
            }
            
            // Merge tags
            if let Some(new_tags) = doc.tags {
                if let Some(base_tags) = &mut base_api.tags {
                    base_tags.extend(new_tags);
                } else {
                    base_api.tags = Some(new_tags);
                }
            }
        )*

        // Add security schemes
        if let Some(components) = base_api.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                utoipa::openapi::security::SecurityScheme::Http(
                    utoipa::openapi::security::Http::new(
                        utoipa::openapi::security::HttpAuthScheme::Bearer,
                    ),
                ),
            );
        } else {
            base_api.components = Some(
                utoipa::openapi::ComponentsBuilder::new()
                    .security_scheme(
                        "bearer_auth",
                        utoipa::openapi::security::SecurityScheme::Http(
                            utoipa::openapi::security::Http::new(
                                utoipa::openapi::security::HttpAuthScheme::Bearer,
                            ),
                        ),
                    )
                    .build(),
            );
        }

        base_api
    }};
}

/// Generate macro call untuk semua docs
/// Usage: let openapi = generate_openapi!();
#[macro_export]
macro_rules! generate_openapi {
    () => {{
        merge_api_docs!(
            docs::academic_year_docs::AcademicYearApiDoc,
            docs::auth_docs::AuthApiDoc,
            docs::role_docs::RoleApiDoc,
            docs::user_docs::UserApiDoc,
        )
    }};
}
